//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceClient
    {
        public int Id { get; set; }
        public Nullable<int> Service { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<int> Client { get; set; }
    
        public virtual Service Service1 { get; set; }
        public virtual User User { get; set; }
    }
}
